### ISSUE TITLE
Feature Request: Highlight the URL Bar

### ISSUE THREAD

**Issue by T3ch404** [excitedleigh/newtab#9]
When opening new tabs, I often go straight to typing in a Google search or a website URL. With the newtab extension installed, it appears to place the cursor at the start of the URL which means my Google searches end up with "localhost:8080" at the end of them (or whatever site I've set to my homepage).
![Screenshot 2024-07-01 113015](https://github.com/daisylb/newtab/assets/45699180/7a5b0c08-cfdc-48af-a4bf-44bbe15d90a3)

It would be awesome if the newtab extension would highlight the contents of the URL bar when opening a new tab so anything that is typed immediately overwrites the contents of the URL bar.
![Screenshot 2024-07-01 112704](https://github.com/daisylb/newtab/assets/45699180/49183885-afa4-405a-8843-30e8e7756ec3)

I'm not sure if this is something anyone else has had issues with, but I think this would be a nice quality of life improvement.

**Comment by lwsx** [comment]
Just came here to request this myself, but found a fixed version - see the fork made by Seigiard under the other issue ("Flash Bang screen while loading")

Here is a link: https://addons.mozilla.org/en-US/firefox/addon/new-tab-shows-your-homepage/

It also fixes the "flashbang" issue, that is the extension not properly respecting the dark/white theme selection.

**Comment by T3ch404** [comment]
@lwsx That works great, thanks!
